# Generated by Django 6.0.4 on 2026-04-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='storage_temperature',
            field=models.IntegerField(blank=True, help_text='Please provide storage temperature in Celsius.', null=True),
        ),
    ]
